### ISSUE TITLE
Feature request: Add in-mem `PolicyReportStore{}` implementation

### ISSUE THREAD

**Issue by viccuad** [kubewarden/audit-scanner#107]
Requested by @nnelas, see https://github.com/kubewarden/audit-scanner/issues/102.

Currently, audit-scanner uses this [PolicyReportStore{}](https://github.com/kubewarden/audit-scanner/blob/main/internal/report/store.go#L27-L30) , which uses a k8s client and therefore uses Kubernetes (Etcd) as cache for the PolicyReports.

This store cache is used to see [historical data of audits here](https://github.com/kubewarden/audit-scanner/blob/main/internal/scanner/scanner.go#L141-L154). This means that if nothing has changed in the audit request condition, the audit-scanner then [skips reevaluating that specific case here](https://github.com/kubewarden/audit-scanner/blob/main/internal/scanner/scanner.go#L298-L308).

### Acceptance criteria

1. Create a `store` Go interface that satisfies the current store implementation at [report/store.go ](https://github.com/kubewarden/audit-scanner/blob/main/internal/report/store.go).
1. Refactor current `report/store.go` into `report/store-kubernetes.go`, as an implementation of the store interface.
   - Check that its unit tests pass.
   - Consume the new `store` Go interface in `scanner/scanner.go`, defaulting to the `store-kubernetes` one.
1. Add a new `memory` store with a slice of [PolicyReports{}](https://github.com/kubewarden/audit-scanner/blob/main/internal/report/report.go#L21-L23), each with their [PolicyReportResults{}](https://github.com/kubewarden/audit-scanner/blob/main/internal/report/report.go#L24C1-L26C2). This new memory store could be under another file `report/store-memory.go` for example.
    -  Unit tests for the new store are provided if needed. Given that this is just operating on in-mem arrays, maybe there's not much to write here.
    - This store will then provide the cache functionality and allow for skipping of reevaluation as expected.
1. Provide an optional cli flag, `--store TYPE`, with possible types `memory`, `kubernetes`. Defaults to `--store kubernetes` for ease on first Kubewarden installations.
2. Expose this functionality by adding a new field in the `kubewarden-controller` helm chart.

**Comment by viccuad** [comment]
@kubewarden/kubewarden-developers  could you have a look at the issue and edit as needed?

**Comment by nnelas** [comment]
> @nnelas if you comment on this issue, we can assign it to you!

hallo! sorry for not replying to you sooner, in the meantime I also made a couple of changes to the original PR aligned with your suggestions
