### ISSUE TITLE
Unit test failure: cannot connect to policy server

### ISSUE THREAD

**Issue by flavio** [kubewarden/audit-scanner#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The CI system is currently failing because of this error:

```console
 ok  	github.com/kubewarden/audit-scanner/internal/resources	0.053s	coverage: 64.7% of statements
=== RUN   TestSendRequestToPolicyServer
    scanner_test.go:68: Post "http://localhost:9876/audit/": dial tcp [::1]:9876: connect: connection refused
--- FAIL: TestSendRequestToPolicyServer (0.00s)
```

This can be seen inside of [this run](https://github.com/kubewarden/audit-scanner/actions/runs/4405293120/jobs/7715994866)

### Expected Behavior

The unit tests should be green

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by viccuad** [comment]
Closing this, currently the unit tests are green, and the codebase change since this card was opened.
