### ISSUE TITLE
Update RFCs to reflect changes done to reporting (resource-based reports)

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/audit-scanner#209]
Since we changed the way we store policy reports from namespace-based and clusterwide-based to resource-based, we need to update the following RFCs:

 [RFC-11](https://github.com/kubewarden/rfc/blob/main/rfc/0011-audit-checks.md)

[RFC-12](https://github.com/kubewarden/rfc/blob/main/rfc/0012-policy-report.md)

**Comment by jvanz** [comment]
RFCs are updated. Closing issue.
