### ISSUE TITLE
audit-scanner - MVP Stage 5.2 - reuse results from previous evaluations

### ISSUE THREAD

**Issue by flavio** [kubewarden/audit-scanner#44]
Leverage previous `PolicyReport` objects as a cache for evaluations
Note: this can be done in parallel of stage 5.1

### Acceptance criteria:
 - See [step 5 of audit RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0011-audit-checks.md#step-5-attempt-to-reuse-previous-evaluation-results)
 - We have unit tests
 - We have integration test **if needed**

**Comment by jvanz** [comment]
I'm moving this to block to wait for a @viccuad review.
